### ISSUE TITLE
Is it possible for CI to function if only the git URL is in the SPD?

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/spack_packages#32]
Provided by @echus:
```
==> [2023-08-03-05:19:21.845836] Error: Can't extrapolate a URL for version 3-build-ci because package mom5 defines no URLs
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/fetch_strategy.py", line 1478, in _extrapolate
    return URLFetchStrategy(pkg.url_for_version(version), fetch_options=pkg.fetch_options)
  File "/opt/spack/lib/spack/spack/package_base.py", line 896, in url_for_version
    return self._implement_all_urls_for_version(version)[0]
  File "/opt/spack/lib/spack/spack/package_base.py", line 962, in _implement_all_urls_for_version
    raise NoURLError(self.__class__)
spack.package_base.NoURLError: Package Mom5 has no version with a URL.
```

**Comment by harshula** [comment]
The command being executed is:
```
spack -d install --only package --no-checksum ${{ inputs.package-name }}@=$GITHUB_REF_NAME%${{ inputs.compiler-name }}@${{ inputs.compiler-version }}
```
e.g.
```
spack -d install --only package --no-checksum mom5@=$GITHUB_HEAD_REF%intel@2021.1.2
```
Where, `GITHUB_HEAD_REF=3-build-ci`

**Comment by aidanheerdegen** [comment]
I thought this was interesting

https://github.com/spack/spack/issues/2788#issuecomment-346624571

> There are actually good reasons to implement both url and url_for_version. url_for_version is used to download packages, but url is used to find new versions of the package with spack versions and spack checksum.

> With that said, there are many packages like pflotran which only use Git for fetching (see https://github.com/spack/spack/issues/3788), or bundle packages that only install other packages and need no URL (see https://github.com/spack/spack/issues/1926). Spack should not crash just because a package does not have a URL.

**Comment by harshula** [comment]
Hi @CodeGat & @echus , Could it be this?

**Comment by harshula** [comment]
When I remove all version() calls in the SPD:

[root@cfa010c3cbac oasis3-mct]# spack install oasis3-mct
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "oasis3-mct"

:house_with_garden:  [11 days ago](https://access-nri.slack.com/archives/C05AWHSU82E/p1698300207862989?thread_ts=1698289130.576279&cid=C05AWHSU82E)

[root@cfa010c3cbac oasis3-mct]# spack install oasis3-mct@master
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "oasis3-mct"

:house_with_garden:  [11 days ago](https://access-nri.slack.com/archives/C05AWHSU82E/p1698300418523889?thread_ts=1698289130.576279&cid=C05AWHSU82E)

[root@cfa010c3cbac oasis3-mct]# spack install oasis3-mct@git.e9640e767ac9f1fad71ddaafa7bbe3f12e8091b6
[+] /opt/spack/opt/spack/linux-rocky8-x86_64/intel-2021.2.0/bzip2-1.0.8-hg2xd66xseykig476usbivbboqlbqgyi
[+] /opt/spack/opt/spack/linux-rocky8-x86_64/intel-2021.2.0/ncurses-6.4-2k7hyztdn6nr3svdpmdcrgkgrnqwqb75
[+] /opt/spack/opt/spack/linux-rocky8-x86_64/intel-2021.2.0/zlib-1.2.13-prjhkvavo6k4dzpqrzv5i7raa6rmaqbc
[+] /opt/spack/opt/spack/linux-rocky8-x86_64/intel-2021.2.0/gmake-4.4.1-nhledudrebl42p5jwemen7j4cv2utqyu

**Comment by harshula** [comment]
When I remove all `version()` and `url_for_version()` calls in the SPD and there's no `url` variable defined:
```
[root@cfa010c3cbac oasis3-mct]# spack install oasis3-mct
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "oasis3-mct"
```
```
[root@cfa010c3cbac oasis3-mct]# spack install oasis3-mct@master
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "oasis3-mct"
```
```
[root@cfa010c3cbac oasis3-mct]# spack install oasis3-mct@git.e9640e767ac9f1fad71ddaafa7bbe3f12e8091b6
[+] /opt/spack/opt/spack/linux-rocky8-x86_64/intel-2021.2.0/bzip2-1.0.8-hg2xd66xseykig476usbivbboqlbqgyi
[+] /opt/spack/opt/spack/linux-rocky8-x86_64/intel-2021.2.0/ncurses-6.4-2k7hyztdn6nr3svdpmdcrgkgrnqwqb75
[+] /opt/spack/opt/spack/linux-rocky8-x86_64/intel-2021.2.0/zlib-1.2.13-prjhkvavo6k4dzpqrzv5i7raa6rmaqbc
[+] /opt/spack/opt/spack/linux-rocky8-x86_64/intel-2021.2.0/gmake-4.4.1-nhledudrebl42p5jwemen7j4cv2utqyu
```
So, yes, it appears an SPD can function with only a `git` URL variable defined. However, the default behaviour might surprise a user because `@git.tag` must be used.
