### ISSUE TITLE
Update MOM5 package to use new option to not use git commit hash versioning

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/spack_packages#35]
This PR adds the ability to build MOM5 in ACCESS-OM2 without the git hash versioning

https://github.com/mom-ocean/MOM5/pull/384

Once it is merged to take advantage of that the `--no_version` option would need to be added here:

https://github.com/ACCESS-NRI/spack_packages/blob/cice5/packages/mom5/package.py#L307-L311

It should probably be made conditional on MOM5 version. Or specify that MOM5 must be that version or greater to build.

**Comment by harshula** [comment]
PR https://github.com/ACCESS-NRI/spack_packages/pull/51 for `--no_version`.
It's not conditional at the moment, but we probably need to make all the SPDs conditional on the new tags that have been introduced.

**Comment by aidanheerdegen** [comment]
Closed by #51
